add pruning and repo check to restic_backup

diff --git a/bin/restic_backup b/bin/restic_backup
--- a/bin/restic_backup
+++ b/bin/restic_backup
@@ -27,5 +27,17 @@ restic --repo "$path" \
        --files-from-verbatim ~/.dotfiles/secrets/backup_dirs_list.txt \
        --password-file "$pwd_file"
 
+echo "Deleting old snapshots..."
+# keep the last 3 snapshots and the most recent snapshot from each of the last 3 months
+restic --repo "$path" \
+         forget \
+        --prune \
+        --keep-last 4 \
+        --keep-monthly 3 \
+        --password-file "$pwd_file"
+
+echo "Checking repo..."
+restic check --repo "$path" --password-file "$pwd_file" || echo "ERROR: Repo check failed." && exit 1
+
 echo "Backup complete. Starting syncthing."
 systemctl --user start syncthing.service
