add BetterDiscord install

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -133,6 +133,36 @@ act() {
 
 ### functions below this line are not included in `all` and should be run manually / if needed
 
+vim_copilot() {
+    git clone https://github.com/github/copilot.vim.git ~/.vim/pack/github/start/copilot.vim
+}
+
+rm_conda() {
+    rm -rf ~/miniconda
+    rm -rf ~/.condarc ~/.conda ~/.continuum
+    rm -rf ~/miniforge3
+}
+
+install_nodejs() {
+    sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg
+    sudo mkdir -p /etc/apt/keyrings
+    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
+    NODE_MAJOR=21
+    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
+    sudo apt-get update && sudo apt-get install nodejs -y
+    sudo npm install -g pnpm
+}
+
+obsidian_vault() {
+    mkdir -pv ~/repos/obsidian && cd ~/repos/obsidian
+    if [ -d "knowledge-base" ]; then
+        echo "knowledge-base already exists"
+        return
+    fi
+    git clone git@github.com:MaxWolf-01/knowledge-base.git
+    cd knowledge-base && git clone git@github.com:MaxWolf-01/.obsidian-pc.git && mv .obsidian-pc .obsidian
+}
+
 obsidian() {
     appimage="$(find ~/Downloads -name 'Obsidian*.AppImage')"
     if [ -z "$appimage" ]; then
@@ -152,24 +182,22 @@ obsidian() {
     echo "Obsidian app set up."
 }
 
-vim_copilot() {
-    git clone https://github.com/github/copilot.vim.git ~/.vim/pack/github/start/copilot.vim
+discord() {
+  # check if npm and pnpm are installed
+  if ! command -v npm &> /dev/null || ! command -v pnpm &> /dev/null; then
+    echo "npm or pnpm not found. Run './setup install_nodejs'"
+    return
+  fi
+  cd ~/repos/tools && git clone https://github.com/BetterDiscord/BetterDiscord.git
+  cd BetterDiscord
+  pnpm install
+  pnpm build
+  pnpm inject
+  find ~/.dotfiles/desktop/discord/themes -type f -exec ln -sf {} ~/.config/BetterDiscord/themes/ \;
+  wget https://discordstyles.github.io/DarkMatter/DarkMatter.theme.css -O ~/.config/BetterDiscord/themes/DarkMatter.theme.css
 }
 
-rm_conda() {
-    rm -rf ~/miniconda
-    rm -rf ~/.condarc ~/.conda ~/.continuum
-    rm -rf ~/miniforge3
-}
-
-install_nodejs() {
-    sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg
-    sudo mkdir -p /etc/apt/keyrings
-    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
-    NODE_MAJOR=21
-    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
-    sudo apt-get update && sudo apt-get install nodejs -y
-}
+### Networking etc
 
 wireguard_client() {
   sudo apt update && sudo apt install -y wireguard resolveconf
@@ -186,16 +214,6 @@ wireguard_client() {
 sshkeys() {
     ssh-keygen -t rsa -b 4096
     echo "Use 'ssh-copy-id <user>@<host>' or '<host>' to add keys to hosts"
-}
-
-obsidian_vault() {
-    mkdir -pv ~/repos/obsidian && cd ~/repos/obsidian
-    if [ -d "knowledge-base" ]; then
-        echo "knowledge-base already exists"
-        return
-    fi
-    git clone git@github.com:MaxWolf-01/knowledge-base.git
-    cd knowledge-base && git clone git@github.com:MaxWolf-01/.obsidian-pc.git && mv .obsidian-pc .obsidian
 }
 
 spg_vpn() {
