add cargo, dysk, more consistent naming

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -31,7 +31,8 @@ minimal() {
 
     zsh zsh/plugin-files/zap_zsh_install # minimal zsh plugin manager
     curl -LsSf https://astral.sh/uv/install.sh | sh
-    install_brew
+    get_brew
+    get_cargo
 
     touch ~/.local_exports
 }
@@ -48,8 +49,8 @@ cli() {
 
     fuzzy_finder
     brew install zoxide fastfetch
-
-    setup_nvim
+    get_dysk
+    get_nvim
 
     # htop but based (install from source for gpu support)
     cd "$HOME/repos/tools" && { if [ -d "btop" ]; then cd btop && git pull; else git clone --depth 1 https://github.com/aristocratos/btop.git && cd btop; fi; sudo make && sudo make install; }
@@ -122,7 +123,7 @@ fuzzy_finder() {
     cd ~/.fzf && git pull && ~/.fzf/install
 }
 
-install_brew() {
+get_brew() {
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 }
 
@@ -143,7 +144,7 @@ mamba() {
 }
 
 
-setup_nvim() {
+get_nvim() {
     local appimage_url="https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage"
     local appimage_dir="$HOME/applications"
     local appimage_path="$appimage_dir/nvim.AppImage"
@@ -238,7 +239,7 @@ syncthing () {
     # todo make syncthingtray work vis apt
 }
 
-install_nodejs() {
+get_nodejs() {
     sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg
     sudo mkdir -p /etc/apt/keyrings
     curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
@@ -246,6 +247,14 @@ install_nodejs() {
     echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
     sudo apt-get update && sudo apt-get install nodejs -y
     sudo npm install -g pnpm
+}
+
+get_cargo() {
+    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+}
+
+get_dysk() {
+    cargo install --locked dysk
 }
 
 obsidian_vault() {
@@ -300,7 +309,7 @@ obsidian() {
 
 discord() {  # will setup discord and betterdiscord on first run, update both on subsequent runs; after discord update run this second time to apply betterdiscord changes
   if [ "$EUID" -eq 0 ]; then echo "Don't run as root!"; return; fi
-  if ! command -v npm &> /dev/null || ! command -v pnpm &> /dev/null; then echo "npm or pnpm not found. Run './setup install_nodejs'"; return; fi
+  if ! command -v npm &> /dev/null || ! command -v pnpm &> /dev/null; then echo "npm or pnpm not found. Run './setup get_nodejs'"; return; fi
   cd ~/repos/tools || echo "Error: $HOME/repos/tools does not exist" || exit 1
   if [ -d ~/repos/tools/BetterDiscord ]; then cd BetterDiscord && git pull; else git clone --depth 1 --single-branch -b main https://github.com/BetterDiscord/BetterDiscord.git && cd BetterDiscord; fi;  # get latest betterdiscord
   if [ ! -f discord.old.deb ]; then wget -O discord.deb "https://discord.com/api/download?platform=linux&format=deb" &&  sudo dpkg -i discord.deb && mv discord.deb discord.old.deb; else sudo dpkg -i discord.old.deb && rm discord.old.deb; fi;
