make discord setup update if installed

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -215,17 +215,12 @@ obsidian() {
     echo "Obsidian app set up."
 }
 
-discord() {
-  # check if npm and pnpm are installed
-  if ! command -v npm &> /dev/null || ! command -v pnpm &> /dev/null; then
-    echo "npm or pnpm not found. Run './setup install_nodejs'"
-    return
-  fi
-  cd ~/repos/tools && git clone https://github.com/BetterDiscord/BetterDiscord.git
-  cd BetterDiscord
-  pnpm install
-  pnpm build
-  pnpm inject
+discord() {  # will setup discord and betterdiscord on first run, update both on subsequent runs
+  wget -O discord.deb "https://discord.com/api/download?platform=linux&format=deb" && sudo dpkg -i discord.deb && rm discord.deb
+  if ! command -v npm &> /dev/null || ! command -v pnpm &> /dev/null; then echo "npm or pnpm not found. Run './setup install_nodejs'"; return; fi
+  cd ~/repos/tools
+  if [ -d ~/repos/tools/BetterDiscord ]; then cd BetterDiscord && git pull; else git clone https://github.com/BetterDiscord/BetterDiscord.git && cd BetterDiscord; fi;
+  pnpm install &&  pnpm build && pnpm inject
   find ~/.dotfiles/desktop/discord/themes -type f -exec ln -sf {} ~/.config/BetterDiscord/themes/ \;
   wget https://discordstyles.github.io/DarkMatter/DarkMatter.theme.css -O ~/.config/BetterDiscord/themes/DarkMatter.theme.css
 }
